#!/usr/bin/env bash
# U-C1 deps parity: generate (or drift-check) the project root requirements.txt from
# the union of custom-addons manifest external_dependencies.python. odoo.sh installs
# from root requirements.txt; the local Dockerfile must install the SAME set, else a
# manifest dep absent from requirements.txt passes locally and fails the odoo.sh build.
#
# Usage:
#   gen-requirements.sh <project_repo>            # write <project>/requirements.txt
#   gen-requirements.sh --check <project_repo>    # drift check only (no write)
#
# Drift semantics: M = manifest python deps, R = requirements.txt entries.
#   M\R (manifest dep missing from requirements.txt) = ERROR (breaks odoo.sh build)
#   R\M (requirements.txt entry no manifest declares)  = WARN  (stale / hand-added)
# Versions are intentionally UNPINNED (manifests state names only) — pin separately if
# odoo.sh parity requires exact versions.
set -euo pipefail

CHECK=0
if [ "${1:-}" = "--check" ]; then CHECK=1; shift; fi
PROJECT="${1:?usage: gen-requirements.sh [--check] <project_repo>}"
ADDONS="$PROJECT/custom-addons"
REQ="$PROJECT/requirements.txt"
[ -d "$ADDONS" ] || { echo "[req] no custom-addons at $ADDONS" >&2; exit 2; }

# Manifest python deps (sorted union).
manifest_deps() {
  python3 - "$ADDONS" <<'PY'
import ast,glob,os,sys
root=sys.argv[1]; deps=set()
for m in glob.glob(os.path.join(root,"*","__manifest__.py")):
    try:
        d=ast.literal_eval(open(m,encoding="utf-8").read())
        for p in (d.get("external_dependencies",{}) or {}).get("python",[]) or []:
            deps.add(p.strip())
    except Exception as e:
        # A manifest that fails to parse could hide a python dep -> warn (don't drop silently).
        print("[req] WARNING could not parse %s: %s" % (os.path.basename(os.path.dirname(m)), e), file=sys.stderr)
print("\n".join(sorted(d for d in deps if d)))
PY
}

# Requirements.txt entries reduced to their distribution name (drop version specifiers
# and comments) so drift compares names, not pins.
req_names() {
  [ -f "$REQ" ] || return 0
  tr -d '\r' < "$REQ" \
    | sed -E 's/#.*//; s/[[:space:]]+//g' \
    | grep -v '^$' \
    | sed -E 's/[<>=!~;].*//' \
    | sort -u
}

M="$(manifest_deps)"

if [ "$CHECK" -eq 1 ]; then
  R="$(req_names)"
  missing="$(comm -23 <(printf '%s\n' "$M") <(printf '%s\n' "$R") | grep -v '^$' || true)"
  stale="$(comm -13 <(printf '%s\n' "$M") <(printf '%s\n' "$R") | grep -v '^$' || true)"
  rc=0
  if [ -n "$stale" ]; then
    echo "[req] WARN stale entries in requirements.txt with no manifest declaring them:"
    printf '  - %s\n' $stale
  fi
  if [ -n "$missing" ]; then
    echo "[req] ERROR manifest python deps missing from requirements.txt (would fail odoo.sh build):"
    printf '  - %s\n' $missing
    rc=1
  fi
  [ "$rc" -eq 0 ] && echo "[req] OK requirements.txt covers all manifest python deps ($(printf '%s\n' "$M" | grep -cv '^$') dep(s))"
  exit "$rc"
fi

{
  echo "# Project python dependencies for the odoo.sh build."
  echo "# GENERATED by 00. DATA/harness/gen-requirements.sh from custom-addons manifest"
  echo "# external_dependencies.python — keep in sync (gen-requirements.sh --check)."
  echo "# Names only (unpinned); add version specifiers here if odoo.sh parity needs them."
  printf '%s\n' "$M" | grep -v '^$'
} > "$REQ"
echo "[req] wrote $REQ ($(printf '%s\n' "$M" | grep -cv '^$') dep(s)): $(printf '%s ' $M)"
