#!/usr/bin/env bash
set -euo pipefail

# Regenerate a target project's install-time guidance baseline
# (.ai-auto/guidance-baseline.sha256). Records the sha256 of every guidance doc
# that is currently byte-identical to this AI_AUTO template, so doc-budget.sh can
# exclude inherited-unchanged guidance from the absolute budget. Customized or
# absent docs are left out (they stay budgeted).
#
# Run from the AI_AUTO repo against a target project:
#   scripts/refresh-guidance-baseline.sh /path/to/target-repo
#
# Use after install (install-automation-template.sh calls this) and after
# adopting a newer template into an existing project, so newly-adopted-but-
# unchanged template docs are recognized as inherited again.

TARGET_DIR="${1:-}"
AI_LAB_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TEMPLATE_DIR="${AI_LAB_ROOT}/templates/automation-base"

if [ -z "${TARGET_DIR}" ]; then
  echo "Usage: $0 /path/to/target-repo"
  exit 1
fi
if [ ! -d "${TARGET_DIR}" ]; then
  echo "Target directory does not exist: ${TARGET_DIR}"
  exit 1
fi
if [ ! -d "${TEMPLATE_DIR}" ]; then
  echo "Template directory not found: ${TEMPLATE_DIR}"
  exit 1
fi

is_exempt() {
  # Mirror doc-budget.sh's content/spec exemptions: those are not budgeted
  # guidance, so they never belong in the baseline.
  case "$1" in
    docs/specs/*|docs/reference/*|*.plan.md|*.spec.md) return 0 ;;
  esac
  return 1
}

template_version="$(head -n1 "${TEMPLATE_DIR}/AI_AUTO_TEMPLATE_VERSION" 2>/dev/null | tr -d '\r' || true)"
mkdir -p "${TARGET_DIR}/.ai-auto"

# Enumerate the guidance docs the template ships (same scope as doc-budget's
# primary guidance: AGENTS.md + docs/*.md), so new template docs are picked up
# without editing a hardcoded list.
mapfile -t guidance < <(
  cd "${TEMPLATE_DIR}"
  {
    printf '%s\n' AGENTS.md
    if [ -d docs ]; then
      find docs -name '*.md' -print
    fi
  } | LC_ALL=C sort
)

baseline_file="${TARGET_DIR}/.ai-auto/guidance-baseline.sha256"
recorded=0
customized=0
{
  echo "# AI_AUTO guidance baseline (sha256sum format; template_version=${template_version:-unknown})"
  echo "# Generated by refresh-guidance-baseline.sh. Lists guidance docs byte-identical"
  echo "# to the current AI_AUTO template; doc-budget.sh excludes these from the absolute"
  echo "# budget. Re-run after adopting a newer template into the project."
  for rel in "${guidance[@]}"; do
    if is_exempt "${rel}"; then
      continue
    fi
    tgt="${TARGET_DIR}/${rel}"
    tpl="${TEMPLATE_DIR}/${rel}"
    if [ -f "${tgt}" ] && [ -f "${tpl}" ] && cmp -s "${tgt}" "${tpl}"; then
      ( cd "${TARGET_DIR}" && sha256sum "${rel}" )
      recorded=$((recorded + 1))
    else
      customized=$((customized + 1))
    fi
  done
} > "${baseline_file}"

echo "Refreshed guidance baseline: ${baseline_file}"
echo "  inherited-unchanged docs recorded: ${recorded}"
echo "  customized/absent docs left budgeted: ${customized}"
